baseURL: /
title: Tekton
enableRobotsTXT: true
theme:
  - github.com/google/docsy
  - github.com/google/docsy/dependencies
enableGitInfo: true
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
disableKinds:
  - taxonomy
  - taxonomyTerm
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: manni
enableEmoji: true
ignoreFiles:
  - vendor/.*
rss_sections:
  - blog
permalinks:
  blog: /:section/:year/:month/:day/:slug/
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: G-G2WH79BEEM
languages:
  en:
    title: Tekton
    description: Cloud Native CI/CD
    languageName: English
    weight: 1
params:
  version_menu: Releases
  github_repo: https://github.com/tektoncd/website
  gcs_engine_id: 013756393218025596041:6eajntqsa6c
  ui:
    sidebar_menu_compact: false
    sidebar_menu_foldable: true
    breadcrumb_disable: true
    sidebar_search_disable: false
    navbar_logo: true
    footer_about_disable: false
    feedback:
      enable: true
      yes:
        Thanks! <a href="https://github.com/tektoncd/website/issues/new">Tell us
        how we can further improve</a>.
      no: Sorry about that. <a
        href="https://github.com/tektoncd/website/issues/new">Tell us how we can
        further improve</a>.
  links:
    developer:
      - name: Slack
        url: https://join.slack.com/t/tektoncd/shared_invite/zt-1z8ctzsyv-wLXWwA2Rl3AOhcNGqpWRUw
        icon: fab fa-slack
        desc: Slack Channel for Tekton Project
      - name: GitHub
        url: https://github.com/tektoncd
        icon: fab fa-github
        desc: GitHub organization for the Tekton project
sectionPagesMenu: "docs"
menu:
  docs:
    - name: "Getting Started"
      url: "/docs/getting-started/"
      weight: 1
    - name: "Installation"
      url: "/docs/installation/"
      weight: 2
    - name: "Concepts"
      url: "/docs/concepts/"
      weight: 3
    - name: "How-to Guides"
      url: "/docs/how-to-guides/"
      weight: 4
    - name: "Tasks and Pipelines"
      url: "/docs/pipelines/"
      weight: 5
    - name: "Triggers and EventListeners"
      url: "/docs/triggers/"
      weight: 6
    - name: "Command-Line Interface"
      url: "/docs/cli/"
      weight: 7
    - name: "Supply Chain Security"
      url: "/docs/chains/"
      weight: 8
    - name: "Operator"
      url: "/docs/operator/"
      weight: 9
    - name: "Dashboard"
      url: "/docs/dashboard/"
      weight: 10 
    - name: "Results"
      url: "/docs/results/"
      weight: 11 
    - name: "Contribute"
      url: "/docs/contribute/"
      weight: 100 
